language: node_js

node_js:
  - '10'

script: npm test

notifications:
  email: false

cache:
  directories:
  - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

dist: trusty

sudo: required

before_deploy:
  - npm run build
  - echo -e "node_modules\npackage-lock.json" > .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
    node: 10
